name = "factorio-blueprint-playground"
compatibility_date = "2024-11-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[vars]
ENVIRONMENT = "development"
SENTRY_DSN = "https://1651d9165253e8922a1297481223a7cf@o4509417677914112.ingest.us.sentry.io/4509515420532736"
VITE_SENTRY_DSN = "https://1651d9165253e8922a1297481223a7cf@o4509417677914112.ingest.us.sentry.io/4509515420532736"

[env.production.vars]
ENVIRONMENT = "production"
# - IMGUR_CLIENT_ID: Imgur API client ID
