# Jobs that run on merge_group, meaning they must pass before changes land. They also run on pull_request.

on:
    pull_request:
    merge_group:

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    pre-commit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: actions/setup-python@v6
              with:
                  python-version: '3.x'
            - uses: pre-commit/action@v3.0.1

    eslint:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            checks: write
            pull-requests: write
        steps:
            - uses: actions/checkout@v5
            - uses: jdx/mise-action@v3

            - run: just eslint-ci
              continue-on-error: true

            - uses: ataylorme/eslint-annotate-action@3.0.0
              if: always()

    biome:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: jdx/mise-action@v3

            - run: just biome-ci

    prettier:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: jdx/mise-action@v3

            - run: just prettier-ci

    typecheck:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: jdx/mise-action@v3
            - run: just typecheck-ci

    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: jdx/mise-action@v3
            - run: just build-ci

    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: jdx/mise-action@v3

            - run: just test-ci

    all-checks:
        name: All checks
        needs: [pre-commit, eslint, biome, prettier, typecheck, build, test]
        runs-on: ubuntu-latest
        steps:
            - name: All checks passed
              run: echo "All checks passed!"
